In [1]:
import pandas as pd 
import numpy as np

In [46]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [47]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [48]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [49]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [50]:
label = pd.DataFrame(data)

In [8]:
label

0
0  0.25
1  0.50
2  0.75
3  1.00

In [9]:
data2 = pd.Series([0.25, 0.50, 0.75, 1.0], index = ['a','b', 'c', 'd'])

In [10]:
data2

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [11]:
pop_dict = {'California': 3456834,
            'Texas': 4542514,
            'New York': 2734835,
            'Florida': 6783942,
           'Illinois': 5738393}

In [12]:
population = pd.Series(pop_dict)

In [13]:
population

California    3456834
Texas         4542514
New York      2734835
Florida       6783942
Illinois      5738393
dtype: int64

In [14]:
population[1:4]

Texas       4542514
New York    2734835
Florida     6783942
dtype: int64

In [15]:
population['Texas':'Florida']

Texas       4542514
New York    2734835
Florida     6783942
dtype: int64

In [16]:
area_dict = {'California': 48593,
            'Texas': 57395,
            'Illinois': 39432,
            'Florida': 39358,
            'New York': 93245}

In [17]:
area_dict

{'California': 48593,
 'Texas': 57395,
 'Illinois': 39432,
 'Florida': 39358,
 'New York': 93245}

In [18]:
area = pd.Series(area_dict)

In [19]:
area

California    48593
Texas         57395
Illinois      39432
Florida       39358
New York      93245
dtype: int64

In [20]:
data = pd.DataFrame([population,area])
# data = pd.DataFrame({'Population': population, 'Area': area})

In [21]:
data

California    Texas  New York  Florida  Illinois
0     3456834  4542514   2734835  6783942   5738393
1       48593    57395     93245    39358     39432

In [22]:
data = pd.DataFrame({'Population': population, 'Area': area})

In [23]:
data

Population   Area
California     3456834  48593
Florida        6783942  39358
Illinois       5738393  39432
New York       2734835  93245
Texas          4542514  57395

In [24]:
data.columns

Index(['Population', 'Area'], dtype='object')

In [25]:
data.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [26]:
data2 = pd.DataFrame(data,columns = ['States', 'Population', 'Area'])

In [27]:
data2

States  Population   Area
California     NaN     3456834  48593
Florida        NaN     6783942  39358
Illinois       NaN     5738393  39432
New York       NaN     2734835  93245
Texas          NaN     4542514  57395

In [43]:
table = [{'times':i, 'Product': 5*i} for i in range(1,11)]
tables = pd.DataFrame(table, index=[5 for i in range(10)])

In [44]:
tables

times  Product
5      1        5
5      2       10
5      3       15
5      4       20
5      5       25
5      6       30
5      7       35
5      8       40
5      9       45
5     10       50

In [30]:
data.keys()

Index(['Population', 'Area'], dtype='object')

In [31]:
list(data.items())

[('Population',
  California    3456834
  Florida       6783942
  Illinois      5738393
  New York      2734835
  Texas         4542514
  Name: Population, dtype: int64),
 ('Area',
  California    48593
  Florida       39358
  Illinois      39432
  New York      93245
  Texas         57395
  Name: Area, dtype: int64)]

In [32]:
data['Density'] = data['Population']/data['Area']

In [33]:
data

Population   Area     Density
California     3456834  48593   71.138518
Florida        6783942  39358  172.365008
Illinois       5738393  39432  145.526298
New York       2734835  93245   29.329562
Texas          4542514  57395   79.144769

In [34]:
data.values

array([[3.45683400e+06, 4.85930000e+04, 7.11385179e+01],
       [6.78394200e+06, 3.93580000e+04, 1.72365008e+02],
       [5.73839300e+06, 3.94320000e+04, 1.45526298e+02],
       [2.73483500e+06, 9.32450000e+04, 2.93295619e+01],
       [4.54251400e+06, 5.73950000e+04, 7.91447687e+01]])

In [58]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [57]:
data.index.append('Washington')

TypeError: all inputs must be Index

In [56]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
A = pd.Series([2,4,6], index = [0,1,2])
B = pd.Series([1,3,5], index = [1,2,3])

In [ ]:
A+B

In [ ]:
A.add(B,fill_value = 0)

In [41]:
A = pd.DataFrame(np.random.randint(0,10,(3,3)), columns=list('ABC'))
A

A  B  C
0  8  1  1
1  5  6  5
2  2  9  2

In [42]:
B = pd.DataFrame(np.random.randint(0,20, (2,2)), columns=list('BA'))
B

B   A
0   0  10
1  10   1

In [ ]:
A+B

In [ ]:
A.add(B, fill_value = 5)

In [67]:
A = np.random.randint(10, size=(3,4))

In [68]:
A

array([[2, 7, 5, 1],
       [8, 1, 6, 5],
       [7, 3, 8, 3]])

In [71]:
df = pd.DataFrame(A, columns=list('QRST'))
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  6 -6  1  4
2  5 -4  3  2

In [4]:
data = np.round(np.random.randn(4,6),1)
data

array([[-1.7,  1.6, -0.6, -1.1,  0. ,  0.5],
       [ 1.9,  0.8,  0. ,  1. ,  0.5,  0.3],
       [-0.1, -1.1,  1.2, -1.1,  0.6,  0.2],
       [ 0.9, -1.3,  1.3,  0.5,  1.7, -1. ]])

In [5]:
data[:,::2]

array([[-1.7, -0.6,  0. ],
       [ 1.9,  0. ,  0.5],
       [-0.1,  1.2,  0.6],
       [ 0.9,  1.3,  1.7]])

In [6]:
data[::2,:]

array([[-1.7,  1.6, -0.6, -1.1,  0. ,  0.5],
       [-0.1, -1.1,  1.2, -1.1,  0.6,  0.2]])

In [20]:
data[:, ::2] *= 10

In [21]:
data

array([[-1.7e+09,  1.6e+00, -6.0e+08, -1.1e+00,  0.0e+00,  5.0e-01],
       [ 1.9e+09,  8.0e-01,  0.0e+00,  1.0e+00,  5.0e+08,  3.0e-01],
       [-1.0e+08, -1.1e+00,  1.2e+09, -1.1e+00,  6.0e+08,  2.0e-01],
       [ 9.0e+08, -1.3e+00,  1.3e+09,  5.0e-01,  1.7e+09, -1.0e+00]])

In [3]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
df = 